In [3]:
import pandas as pd
import numpy as np

In [2]:
import pickle

In [6]:
with open('F:\\Pactice ostad data science\\Save model\\model_pickle','rb') as file:
    mod = pickle.load(file)

In [7]:
mod.coef_

array([[135.78767123]])

In [8]:
mod.intercept_

array([180616.43835616])

In [9]:
mod.predict([[5000]])

C:\Users\Hp\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[859554.79452055]])

In [13]:
import joblib as jbl
my_model = jbl.load('F:\\Pactice ostad data science\\Save model\\myjoblib_model') 

In [14]:
my_model.coef_

array([[135.78767123]])

In [16]:
my_model.intercept_

array([180616.43835616])